### ISSUE TITLE
`return_type` behavior

### ISSUE THREAD

**Issue by shashi** [MikeInnes/Mjolnir.jl#2]
```julia
julia> ir = @code_ir 1+2                                                                             [3/281]
1: (%1, %2, %3)  %4 = Base.add_int(%2, %3)
  return %4

julia> Mjolnir.return_type(ir, Nothing, Int, Int)
ERROR: No IR for Tuple{Core.IntrinsicFunction,Int64,Int64}
Stacktrace:
 [1] infercall!(::Mjolnir.Inference, ::Tuple{Mjolnir.Frame,Int64,Int64,Int64}, ::IRTools.Inner.Block, ::Expr
) at /home/shashi/.julia/dev/Mjolnir/src/infer.jl:130
 [2] step!(::Mjolnir.Inference) at /home/shashi/.julia/dev/Mjolnir/src/infer.jl:168
 [3] infer!(::Mjolnir.Inference) at /home/shashi/.julia/dev/Mjolnir/src/infer.jl:197
 [4] return_type(::IRTools.Inner.IR, ::Type{T} where T, ::Vararg{Type{T} where T,N} where N) at /home/shashi
/.julia/dev/Mjolnir/src/infer.jl:226
 [5] top-level scope at REPL[13]:1
 [6] run_backend(::REPL.REPLBackend) at /home/shashi/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
```

I have 2 questions here:

1. why does the test create `add(a,b) = a+b` and infer on that.
2. why is the first argument to `return_type` Nothing?

**Comment by MikeInnes** [comment]
1. In your example no `+` function actually appears in the IR, so Mjolnir can't intercept `+` here and instead hits an unknown function `add_int`. If you were to get IR for `add` it'd have the `+` call in and it would work. As it happens though, there's a workaround for this in `@trace`, which now behaves more intuitively:

```julia
julia> @trace Int+Int
1: (%1 :: const(+), %2 :: Int64, %3 :: Int64)
  %4 = (+)(%2, %3) :: Int64
  return %4
```

2. Strictly speaking it should be `typeof(+)`, i.e. it's the type of the function itself. It happens not to be used in these examples so we use `Nothing` instead.

**Comment by shashi** [comment]
Okay

1. makes sense
2. why does it need the type when the first argument is `+`? I guess `return_type` is internal enough that anything goes though.

**Comment by MikeInnes** [comment]
When you call `@code_ir 1+2` you have type information about all arguments, but it the `@code_lowered` with all type information about the arguments thrown out. (Because the lowered code is created before we have any type information at all, and we want to represent that faithfully.) So to actually infer it you have to put that type info back in, which higher-level functions do for you.
